-- +goose Up
-- Book names for the 66-book canon in Swahili and English (reference data, not licensed text).
-- Names already present (e.g. from the sample seed) are updated to these canonical values.
INSERT INTO bible_book_names (book, lang, name, abbr) VALUES
  ('GEN', 'sw', 'Mwanzo', 'Mwa'),
  ('EXO', 'sw', 'Kutoka', 'Kut'),
  ('LEV', 'sw', 'Mambo ya Walawi', 'Law'),
  ('NUM', 'sw', 'Hesabu', 'Hes'),
  ('DEU', 'sw', 'Kumbukumbu la Torati', 'Kum'),
  ('JOS', 'sw', 'Yoshua', 'Yos'),
  ('JDG', 'sw', 'Waamuzi', 'Amu'),
  ('RUT', 'sw', 'Ruthu', 'Rut'),
  ('1SA', 'sw', '1 Samweli', '1Sam'),
  ('2SA', 'sw', '2 Samweli', '2Sam'),
  ('1KI', 'sw', '1 Wafalme', '1Fal'),
  ('2KI', 'sw', '2 Wafalme', '2Fal'),
  ('1CH', 'sw', '1 Mambo ya Nyakati', '1Nya'),
  ('2CH', 'sw', '2 Mambo ya Nyakati', '2Nya'),
  ('EZR', 'sw', 'Ezra', 'Ezr'),
  ('NEH', 'sw', 'Nehemia', 'Neh'),
  ('EST', 'sw', 'Esta', 'Est'),
  ('JOB', 'sw', 'Ayubu', 'Ayu'),
  ('PSA', 'sw', 'Zaburi', 'Zab'),
  ('PRO', 'sw', 'Mithali', 'Mit'),
  ('ECC', 'sw', 'Mhubiri', 'Mhu'),
  ('SNG', 'sw', 'Wimbo Ulio Bora', 'Wim'),
  ('ISA', 'sw', 'Isaya', 'Isa'),
  ('JER', 'sw', 'Yeremia', 'Yer'),
  ('LAM', 'sw', 'Maombolezo', 'Omb'),
  ('EZK', 'sw', 'Ezekieli', 'Eze'),
  ('DAN', 'sw', 'Danieli', 'Dan'),
  ('HOS', 'sw', 'Hosea', 'Hos'),
  ('JOL', 'sw', 'Yoeli', 'Yoe'),
  ('AMO', 'sw', 'Amosi', 'Amo'),
  ('OBA', 'sw', 'Obadia', 'Oba'),
  ('JON', 'sw', 'Yona', 'Yon'),
  ('MIC', 'sw', 'Mika', 'Mik'),
  ('NAM', 'sw', 'Nahumu', 'Nah'),
  ('HAB', 'sw', 'Habakuki', 'Hab'),
  ('ZEP', 'sw', 'Sefania', 'Sef'),
  ('HAG', 'sw', 'Hagai', 'Hag'),
  ('ZEC', 'sw', 'Zekaria', 'Zek'),
  ('MAL', 'sw', 'Malaki', 'Mal'),
  ('MAT', 'sw', 'Mathayo', 'Mt'),
  ('MRK', 'sw', 'Marko', 'Mk'),
  ('LUK', 'sw', 'Luka', 'Lk'),
  ('JHN', 'sw', 'Yohana', 'Yn'),
  ('ACT', 'sw', 'Matendo ya Mitume', 'Mdo'),
  ('ROM', 'sw', 'Warumi', 'Rum'),
  ('1CO', 'sw', '1 Wakorintho', '1Kor'),
  ('2CO', 'sw', '2 Wakorintho', '2Kor'),
  ('GAL', 'sw', 'Wagalatia', 'Gal'),
  ('EPH', 'sw', 'Waefeso', 'Efe'),
  ('PHP', 'sw', 'Wafilipi', 'Flp'),
  ('COL', 'sw', 'Wakolosai', 'Kol'),
  ('1TH', 'sw', '1 Wathesalonike', '1The'),
  ('2TH', 'sw', '2 Wathesalonike', '2The'),
  ('1TI', 'sw', '1 Timotheo', '1Tim'),
  ('2TI', 'sw', '2 Timotheo', '2Tim'),
  ('TIT', 'sw', 'Tito', 'Tit'),
  ('PHM', 'sw', 'Filemoni', 'Flm'),
  ('HEB', 'sw', 'Waebrania', 'Ebr'),
  ('JAS', 'sw', 'Yakobo', 'Yak'),
  ('1PE', 'sw', '1 Petro', '1Pet'),
  ('2PE', 'sw', '2 Petro', '2Pet'),
  ('1JN', 'sw', '1 Yohana', '1Yn'),
  ('2JN', 'sw', '2 Yohana', '2Yn'),
  ('3JN', 'sw', '3 Yohana', '3Yn'),
  ('JUD', 'sw', 'Yuda', 'Yud'),
  ('REV', 'sw', 'Ufunuo', 'Ufu'),
  ('GEN', 'en', 'Genesis', 'Gen'),
  ('EXO', 'en', 'Exodus', 'Exod'),
  ('LEV', 'en', 'Leviticus', 'Lev'),
  ('NUM', 'en', 'Numbers', 'Num'),
  ('DEU', 'en', 'Deuteronomy', 'Deut'),
  ('JOS', 'en', 'Joshua', 'Josh'),
  ('JDG', 'en', 'Judges', 'Judg'),
  ('RUT', 'en', 'Ruth', 'Ruth'),
  ('1SA', 'en', '1 Samuel', '1Sam'),
  ('2SA', 'en', '2 Samuel', '2Sam'),
  ('1KI', 'en', '1 Kings', '1Kgs'),
  ('2KI', 'en', '2 Kings', '2Kgs'),
  ('1CH', 'en', '1 Chronicles', '1Chr'),
  ('2CH', 'en', '2 Chronicles', '2Chr'),
  ('EZR', 'en', 'Ezra', 'Ezra'),
  ('NEH', 'en', 'Nehemiah', 'Neh'),
  ('EST', 'en', 'Esther', 'Esth'),
  ('JOB', 'en', 'Job', 'Job'),
  ('PSA', 'en', 'Psalms', 'Ps'),
  ('PRO', 'en', 'Proverbs', 'Prov'),
  ('ECC', 'en', 'Ecclesiastes', 'Eccl'),
  ('SNG', 'en', 'Song of Solomon', 'Song'),
  ('ISA', 'en', 'Isaiah', 'Isa'),
  ('JER', 'en', 'Jeremiah', 'Jer'),
  ('LAM', 'en', 'Lamentations', 'Lam'),
  ('EZK', 'en', 'Ezekiel', 'Ezek'),
  ('DAN', 'en', 'Daniel', 'Dan'),
  ('HOS', 'en', 'Hosea', 'Hos'),
  ('JOL', 'en', 'Joel', 'Joel'),
  ('AMO', 'en', 'Amos', 'Amos'),
  ('OBA', 'en', 'Obadiah', 'Obad'),
  ('JON', 'en', 'Jonah', 'Jonah'),
  ('MIC', 'en', 'Micah', 'Mic'),
  ('NAM', 'en', 'Nahum', 'Nah'),
  ('HAB', 'en', 'Habakkuk', 'Hab'),
  ('ZEP', 'en', 'Zephaniah', 'Zeph'),
  ('HAG', 'en', 'Haggai', 'Hag'),
  ('ZEC', 'en', 'Zechariah', 'Zech'),
  ('MAL', 'en', 'Malachi', 'Mal'),
  ('MAT', 'en', 'Matthew', 'Matt'),
  ('MRK', 'en', 'Mark', 'Mark'),
  ('LUK', 'en', 'Luke', 'Luke'),
  ('JHN', 'en', 'John', 'John'),
  ('ACT', 'en', 'Acts', 'Acts'),
  ('ROM', 'en', 'Romans', 'Rom'),
  ('1CO', 'en', '1 Corinthians', '1Cor'),
  ('2CO', 'en', '2 Corinthians', '2Cor'),
  ('GAL', 'en', 'Galatians', 'Gal'),
  ('EPH', 'en', 'Ephesians', 'Eph'),
  ('PHP', 'en', 'Philippians', 'Phil'),
  ('COL', 'en', 'Colossians', 'Col'),
  ('1TH', 'en', '1 Thessalonians', '1Thess'),
  ('2TH', 'en', '2 Thessalonians', '2Thess'),
  ('1TI', 'en', '1 Timothy', '1Tim'),
  ('2TI', 'en', '2 Timothy', '2Tim'),
  ('TIT', 'en', 'Titus', 'Titus'),
  ('PHM', 'en', 'Philemon', 'Phlm'),
  ('HEB', 'en', 'Hebrews', 'Heb'),
  ('JAS', 'en', 'James', 'Jas'),
  ('1PE', 'en', '1 Peter', '1Pet'),
  ('2PE', 'en', '2 Peter', '2Pet'),
  ('1JN', 'en', '1 John', '1John'),
  ('2JN', 'en', '2 John', '2John'),
  ('3JN', 'en', '3 John', '3John'),
  ('JUD', 'en', 'Jude', 'Jude'),
  ('REV', 'en', 'Revelation', 'Rev')
ON CONFLICT (book, lang) DO UPDATE SET name = EXCLUDED.name, abbr = EXCLUDED.abbr;

-- +goose Down
DELETE FROM bible_book_names WHERE lang IN ('sw', 'en');
