//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for FeedKind.
const (
	FeedKindAudioBible    FeedKind = "audio_bible"
	FeedKindDevotional    FeedKind = "devotional"
	FeedKindEgwQuote      FeedKind = "egw_quote"
	FeedKindHealth        FeedKind = "health"
	FeedKindHymn          FeedKind = "hymn"
	FeedKindProphecy      FeedKind = "prophecy"
	FeedKindSabbathSchool FeedKind = "sabbath_school"
	FeedKindSermon        FeedKind = "sermon"
	FeedKindVerse         FeedKind = "verse"
	FeedKindYouth         FeedKind = "youth"
)

// Valid indicates whether the value is a known member of the FeedKind enum.
func (e FeedKind) Valid() bool {
	switch e {
	case FeedKindAudioBible:
		return true
	case FeedKindDevotional:
		return true
	case FeedKindEgwQuote:
		return true
	case FeedKindHealth:
		return true
	case FeedKindHymn:
		return true
	case FeedKindProphecy:
		return true
	case FeedKindSabbathSchool:
		return true
	case FeedKindSermon:
		return true
	case FeedKindVerse:
		return true
	case FeedKindYouth:
		return true
	default:
		return false
	}
}

// Defines values for FeedLinkTarget.
const (
	FeedLinkTargetBelief       FeedLinkTarget = "belief"
	FeedLinkTargetCourseLesson FeedLinkTarget = "course_lesson"
	FeedLinkTargetEgwParagraph FeedLinkTarget = "egw_paragraph"
	FeedLinkTargetFeedItem     FeedLinkTarget = "feed_item"
	FeedLinkTargetHymn         FeedLinkTarget = "hymn"
	FeedLinkTargetSsDay        FeedLinkTarget = "ss_day"
	FeedLinkTargetVerse        FeedLinkTarget = "verse"
)

// Valid indicates whether the value is a known member of the FeedLinkTarget enum.
func (e FeedLinkTarget) Valid() bool {
	switch e {
	case FeedLinkTargetBelief:
		return true
	case FeedLinkTargetCourseLesson:
		return true
	case FeedLinkTargetEgwParagraph:
		return true
	case FeedLinkTargetFeedItem:
		return true
	case FeedLinkTargetHymn:
		return true
	case FeedLinkTargetSsDay:
		return true
	case FeedLinkTargetVerse:
		return true
	default:
		return false
	}
}

// Defines values for HealthDb.
const (
	HealthDbDown HealthDb = "down"
	HealthDbOk   HealthDb = "ok"
)

// Valid indicates whether the value is a known member of the HealthDb enum.
func (e HealthDb) Valid() bool {
	switch e {
	case HealthDbDown:
		return true
	case HealthDbOk:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	HealthStatusDegraded HealthStatus = "degraded"
	HealthStatusOk       HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case HealthStatusDegraded:
		return true
	case HealthStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for MediaKind.
const (
	Audio MediaKind = "audio"
	Image MediaKind = "image"
	Video MediaKind = "video"
)

// Valid indicates whether the value is a known member of the MediaKind enum.
func (e MediaKind) Valid() bool {
	switch e {
	case Audio:
		return true
	case Image:
		return true
	case Video:
		return true
	default:
		return false
	}
}

// BibleChapter defines model for BibleChapter.
type BibleChapter struct {
	Book string `json:"book"`

	// BookName Localised to the translation's language when known.
	BookName    *string `json:"book_name,omitempty"`
	Chapter     int     `json:"chapter"`
	Parallel    *string `json:"parallel,omitempty"`
	Translation string  `json:"translation"`
	Verses      []Verse `json:"verses"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// FeedItem defines model for FeedItem.
type FeedItem struct {
	// AltBody Parallel-language text.
	AltBody   *string            `json:"alt_body,omitempty"`
	AltLang   *string            `json:"alt_lang,omitempty"`
	Audience  *[]string          `json:"audience,omitempty"`
	Body      string             `json:"body"`
	CtaLabel  *string            `json:"cta_label,omitempty"`
	CtaTarget *string            `json:"cta_target,omitempty"`
	Id        openapi_types.UUID `json:"id"`
	Kicker    string             `json:"kicker"`
	Kind      FeedKind           `json:"kind"`
	Lang      string             `json:"lang"`
	Media     *Media             `json:"media,omitempty"`
	PublishAt time.Time          `json:"publish_at"`

	// RefLabel Example: YOHANA 3:16
	RefLabel *string `json:"ref_label,omitempty"`
	Source   *string `json:"source,omitempty"`
}

// FeedItemDetail defines model for FeedItemDetail.
type FeedItemDetail struct {
	// AltBody Parallel-language text.
	AltBody   *string            `json:"alt_body,omitempty"`
	AltLang   *string            `json:"alt_lang,omitempty"`
	Audience  *[]string          `json:"audience,omitempty"`
	Body      string             `json:"body"`
	CtaLabel  *string            `json:"cta_label,omitempty"`
	CtaTarget *string            `json:"cta_target,omitempty"`
	Id        openapi_types.UUID `json:"id"`
	Kicker    string             `json:"kicker"`
	Kind      FeedKind           `json:"kind"`
	Lang      string             `json:"lang"`
	Links     []FeedLink         `json:"links"`
	Media     *Media             `json:"media,omitempty"`
	PublishAt time.Time          `json:"publish_at"`

	// RefLabel Example: YOHANA 3:16
	RefLabel *string `json:"ref_label,omitempty"`
	Source   *string `json:"source,omitempty"`
}

// FeedKind defines model for FeedKind.
type FeedKind string

// FeedLink defines model for FeedLink.
type FeedLink struct {
	Label     string         `json:"label"`
	Target    FeedLinkTarget `json:"target"`
	TargetRef string         `json:"target_ref"`
}

// FeedLinkTarget defines model for FeedLink.Target.
type FeedLinkTarget string

// FeedPage defines model for FeedPage.
type FeedPage struct {
	Items []FeedItem `json:"items"`

	// Lang Language actually served (falls back to en when the requested language has no items).
	Lang string `json:"lang"`

	// NextCursor Absent on the last page.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// Health defines model for Health.
type Health struct {
	Db     HealthDb     `json:"db"`
	Status HealthStatus `json:"status"`
}

// HealthDb defines model for Health.Db.
type HealthDb string

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Media defines model for Media.
type Media struct {
	// Bytes Shown as tap-to-load size in data-saver mode.
	Bytes     *int64             `json:"bytes,omitempty"`
	DurationS *int               `json:"duration_s,omitempty"`
	HlsUrl    *string            `json:"hls_url,omitempty"`
	Id        openapi_types.UUID `json:"id"`
	Kind      MediaKind          `json:"kind"`
	Url       string             `json:"url"`
}

// MediaKind defines model for Media.Kind.
type MediaKind string

// Pack defines model for Pack.
type Pack struct {
	Bytes  int64  `json:"bytes"`
	Lang   string `json:"lang"`
	Sha256 string `json:"sha256"`

	// Slug Example: bible-SUV
	Slug    string `json:"slug"`
	Url     string `json:"url"`
	Version int    `json:"version"`
}

// Verse defines model for Verse.
type Verse struct {
	// OsisRef Example: JHN.3.16
	OsisRef      string  `json:"osis_ref"`
	ParallelText *string `json:"parallel_text,omitempty"`
	Text         string  `json:"text"`
	Verse        int     `json:"verse"`
}

// Lang Example: sw
type Lang = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// GetBibleChapterParams defines parameters for GetBibleChapter.
type GetBibleChapterParams struct {
	// Parallel Second translation code to align verse-by-verse.
	Parallel *string `form:"parallel,omitempty" json:"parallel,omitempty"`
}

// ListFeedParams defines parameters for ListFeed.
type ListFeedParams struct {
	// Lang BCP 47 language (sw, en, fr). Defaults to sw.
	Lang *Lang `form:"lang,omitempty" json:"lang,omitempty"`

	// Cursor Opaque cursor from a previous page's `next_cursor`.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Kinds Comma-separated feed kinds to include (default all).
	Kinds *string `form:"kinds,omitempty" json:"kinds,omitempty"`
	Limit *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListPacksParams defines parameters for ListPacks.
type ListPacksParams struct {
	// Lang BCP 47 language (sw, en, fr). Defaults to sw.
	Lang *Lang `form:"lang,omitempty" json:"lang,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth Liveness + database check
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// GetBibleChapter Verses of one chapter, optionally with a parallel translation
	// (GET /v1/bible/{translation}/{book}/{chapter})
	GetBibleChapter(w http.ResponseWriter, r *http.Request, translation string, book string, chapter int, params GetBibleChapterParams)
	// ListFeed Published feed items, newest first, cursor-paginated
	// (GET /v1/feed)
	ListFeed(w http.ResponseWriter, r *http.Request, params ListFeedParams)
	// GetFeedItem One feed item plus its "Soma pamoja" links
	// (GET /v1/feed/{id})
	GetFeedItem(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// ListPacks Offline pack manifest (latest version per slug)
	// (GET /v1/packs)
	ListPacks(w http.ResponseWriter, r *http.Request, params ListPacksParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBibleChapter operation middleware
func (siw *ServerInterfaceWrapper) GetBibleChapter(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "translation" -------------
	var translation string

	err = runtime.BindStyledParameterWithOptions("simple", "translation", r.PathValue("translation"), &translation, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "translation", Err: err})
		return
	}

	// ------------- Path parameter "book" -------------
	var book string

	err = runtime.BindStyledParameterWithOptions("simple", "book", r.PathValue("book"), &book, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "book", Err: err})
		return
	}

	// ------------- Path parameter "chapter" -------------
	var chapter int

	err = runtime.BindStyledParameterWithOptions("simple", "chapter", r.PathValue("chapter"), &chapter, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "chapter", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetBibleChapterParams

	// ------------- Optional query parameter "parallel" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "parallel", r.URL.Query(), &params.Parallel, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "parallel"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "parallel", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBibleChapter(w, r, translation, book, chapter, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListFeed operation middleware
func (siw *ServerInterfaceWrapper) ListFeed(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListFeedParams

	// ------------- Optional query parameter "lang" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "lang", r.URL.Query(), &params.Lang, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "lang"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lang", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "kinds" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "kinds", r.URL.Query(), &params.Kinds, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "kinds"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "kinds", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListFeed(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFeedItem operation middleware
func (siw *ServerInterfaceWrapper) GetFeedItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFeedItem(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPacks operation middleware
func (siw *ServerInterfaceWrapper) ListPacks(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPacksParams

	// ------------- Optional query parameter "lang" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "lang", r.URL.Query(), &params.Lang, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "lang"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lang", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPacks(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/packs", wrapper.ListPacks)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/feed", wrapper.ListFeed)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/feed/{id}", wrapper.GetFeedItem)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/bible/{translation}/{book}/{chapter}", wrapper.GetBibleChapter)

	return m
}

type BadRequestJSONResponse Error

type NotFoundJSONResponse Error

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealth503JSONResponse Health

func (response GetHealth503JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetBibleChapterRequestObject struct {
	Translation string `json:"translation"`
	Book        string `json:"book"`
	Chapter     int    `json:"chapter"`
	Params      GetBibleChapterParams
}

type GetBibleChapterResponseObject interface {
	VisitGetBibleChapterResponse(w http.ResponseWriter) error
}

type GetBibleChapter200JSONResponse BibleChapter

func (response GetBibleChapter200JSONResponse) VisitGetBibleChapterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetBibleChapter404JSONResponse struct{ NotFoundJSONResponse }

func (response GetBibleChapter404JSONResponse) VisitGetBibleChapterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListFeedRequestObject struct {
	Params ListFeedParams
}

type ListFeedResponseObject interface {
	VisitListFeedResponse(w http.ResponseWriter) error
}

type ListFeed200JSONResponse FeedPage

func (response ListFeed200JSONResponse) VisitListFeedResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListFeed400JSONResponse struct{ BadRequestJSONResponse }

func (response ListFeed400JSONResponse) VisitListFeedResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetFeedItemRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetFeedItemResponseObject interface {
	VisitGetFeedItemResponse(w http.ResponseWriter) error
}

type GetFeedItem200JSONResponse FeedItemDetail

func (response GetFeedItem200JSONResponse) VisitGetFeedItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetFeedItem404JSONResponse struct{ NotFoundJSONResponse }

func (response GetFeedItem404JSONResponse) VisitGetFeedItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListPacksRequestObject struct {
	Params ListPacksParams
}

type ListPacksResponseObject interface {
	VisitListPacksResponse(w http.ResponseWriter) error
}

type ListPacks200JSONResponse struct {
	Packs []Pack `json:"packs"`
}

func (response ListPacks200JSONResponse) VisitListPacksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListPacks400JSONResponse struct{ BadRequestJSONResponse }

func (response ListPacks400JSONResponse) VisitListPacksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetHealth Liveness + database check
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// GetBibleChapter Verses of one chapter, optionally with a parallel translation
	// (GET /v1/bible/{translation}/{book}/{chapter})
	GetBibleChapter(ctx context.Context, request GetBibleChapterRequestObject) (GetBibleChapterResponseObject, error)
	// ListFeed Published feed items, newest first, cursor-paginated
	// (GET /v1/feed)
	ListFeed(ctx context.Context, request ListFeedRequestObject) (ListFeedResponseObject, error)
	// GetFeedItem One feed item plus its "Soma pamoja" links
	// (GET /v1/feed/{id})
	GetFeedItem(ctx context.Context, request GetFeedItemRequestObject) (GetFeedItemResponseObject, error)
	// ListPacks Offline pack manifest (latest version per slug)
	// (GET /v1/packs)
	ListPacks(ctx context.Context, request ListPacksRequestObject) (ListPacksResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetBibleChapter operation middleware
func (sh *strictHandler) GetBibleChapter(w http.ResponseWriter, r *http.Request, translation string, book string, chapter int, params GetBibleChapterParams) {
	var request GetBibleChapterRequestObject

	request.Translation = translation
	request.Book = book
	request.Chapter = chapter
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetBibleChapter(ctx, request.(GetBibleChapterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBibleChapter")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetBibleChapterResponseObject); ok {
		if err := validResponse.VisitGetBibleChapterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListFeed operation middleware
func (sh *strictHandler) ListFeed(w http.ResponseWriter, r *http.Request, params ListFeedParams) {
	var request ListFeedRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListFeed(ctx, request.(ListFeedRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListFeed")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListFeedResponseObject); ok {
		if err := validResponse.VisitListFeedResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetFeedItem operation middleware
func (sh *strictHandler) GetFeedItem(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetFeedItemRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetFeedItem(ctx, request.(GetFeedItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetFeedItem")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetFeedItemResponseObject); ok {
		if err := validResponse.VisitGetFeedItemResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListPacks operation middleware
func (sh *strictHandler) ListPacks(w http.ResponseWriter, r *http.Request, params ListPacksParams) {
	var request ListPacksRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListPacks(ctx, request.(ListPacksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPacks")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListPacksResponseObject); ok {
		if err := validResponse.VisitListPacksResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
