// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: content.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getBookName = `-- name: GetBookName :one
SELECT name FROM bible_book_names WHERE book = $1 AND lang = $2
`

type GetBookNameParams struct {
	Book string
	Lang string
}

func (q *Queries) GetBookName(ctx context.Context, arg GetBookNameParams) (string, error) {
	row := q.db.QueryRow(ctx, getBookName, arg.Book, arg.Lang)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getFeedItem = `-- name: GetFeedItem :one
SELECT f.id, f.kind, f.lang, f.kicker, f.source, f.body, f.ref_label,
       f.alt_lang, f.alt_body, f.cta_label, f.cta_target, f.audience, f.publish_at,
       m.id AS media_id, m.kind AS media_kind, m.url AS media_url, m.hls_url AS media_hls_url,
       m.bytes AS media_bytes, m.duration_s AS media_duration_s
FROM feed_items f
LEFT JOIN media m ON m.id = f.media_id
WHERE f.id = $1 AND f.status = 'published' AND f.publish_at <= now()
`

type GetFeedItemRow struct {
	ID             uuid.UUID
	Kind           FeedKind
	Lang           string
	Kicker         string
	Source         pgtype.Text
	Body           string
	RefLabel       pgtype.Text
	AltLang        pgtype.Text
	AltBody        pgtype.Text
	CtaLabel       pgtype.Text
	CtaTarget      pgtype.Text
	Audience       []string
	PublishAt      pgtype.Timestamptz
	MediaID        uuid.NullUUID
	MediaKind      NullMediaKind
	MediaUrl       pgtype.Text
	MediaHlsUrl    pgtype.Text
	MediaBytes     pgtype.Int8
	MediaDurationS pgtype.Int4
}

func (q *Queries) GetFeedItem(ctx context.Context, id uuid.UUID) (GetFeedItemRow, error) {
	row := q.db.QueryRow(ctx, getFeedItem, id)
	var i GetFeedItemRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Lang,
		&i.Kicker,
		&i.Source,
		&i.Body,
		&i.RefLabel,
		&i.AltLang,
		&i.AltBody,
		&i.CtaLabel,
		&i.CtaTarget,
		&i.Audience,
		&i.PublishAt,
		&i.MediaID,
		&i.MediaKind,
		&i.MediaUrl,
		&i.MediaHlsUrl,
		&i.MediaBytes,
		&i.MediaDurationS,
	)
	return i, err
}

const getTranslation = `-- name: GetTranslation :one
SELECT id, code, lang FROM bible_translations WHERE code = $1
`

type GetTranslationRow struct {
	ID   int32
	Code string
	Lang string
}

func (q *Queries) GetTranslation(ctx context.Context, code string) (GetTranslationRow, error) {
	row := q.db.QueryRow(ctx, getTranslation, code)
	var i GetTranslationRow
	err := row.Scan(&i.ID, &i.Code, &i.Lang)
	return i, err
}

const listChapterVerses = `-- name: ListChapterVerses :many
SELECT osis_ref, verse, text
FROM verses
WHERE translation_id = $1 AND book = $2 AND chapter = $3
ORDER BY verse
`

type ListChapterVersesParams struct {
	TranslationID int32
	Book          string
	Chapter       int32
}

type ListChapterVersesRow struct {
	OsisRef string
	Verse   int32
	Text    string
}

func (q *Queries) ListChapterVerses(ctx context.Context, arg ListChapterVersesParams) ([]ListChapterVersesRow, error) {
	rows, err := q.db.Query(ctx, listChapterVerses, arg.TranslationID, arg.Book, arg.Chapter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChapterVersesRow{}
	for rows.Next() {
		var i ListChapterVersesRow
		if err := rows.Scan(&i.OsisRef, &i.Verse, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeed = `-- name: ListFeed :many
SELECT f.id, f.kind, f.lang, f.kicker, f.source, f.body, f.ref_label,
       f.alt_lang, f.alt_body, f.cta_label, f.cta_target, f.audience, f.publish_at,
       m.id AS media_id, m.kind AS media_kind, m.url AS media_url, m.hls_url AS media_hls_url,
       m.bytes AS media_bytes, m.duration_s AS media_duration_s
FROM feed_items f
LEFT JOIN media m ON m.id = f.media_id
WHERE f.status = 'published'
  AND f.publish_at <= now()
  AND f.lang = $1
  AND (cardinality($2::text[]) = 0 OR f.kind::text = ANY($2::text[]))
  AND ($3::timestamptz IS NULL
       OR (f.publish_at, f.id) < ($3::timestamptz, $4::uuid))
ORDER BY f.publish_at DESC, f.id DESC
LIMIT $5
`

type ListFeedParams struct {
	Lang     string
	Kinds    []string
	CursorAt pgtype.Timestamptz
	CursorID uuid.NullUUID
	Lim      int32
}

type ListFeedRow struct {
	ID             uuid.UUID
	Kind           FeedKind
	Lang           string
	Kicker         string
	Source         pgtype.Text
	Body           string
	RefLabel       pgtype.Text
	AltLang        pgtype.Text
	AltBody        pgtype.Text
	CtaLabel       pgtype.Text
	CtaTarget      pgtype.Text
	Audience       []string
	PublishAt      pgtype.Timestamptz
	MediaID        uuid.NullUUID
	MediaKind      NullMediaKind
	MediaUrl       pgtype.Text
	MediaHlsUrl    pgtype.Text
	MediaBytes     pgtype.Int8
	MediaDurationS pgtype.Int4
}

// Keyset pagination on (publish_at DESC, id DESC). Pass NULL cursor fields for the first page.
func (q *Queries) ListFeed(ctx context.Context, arg ListFeedParams) ([]ListFeedRow, error) {
	rows, err := q.db.Query(ctx, listFeed,
		arg.Lang,
		arg.Kinds,
		arg.CursorAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeedRow{}
	for rows.Next() {
		var i ListFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Lang,
			&i.Kicker,
			&i.Source,
			&i.Body,
			&i.RefLabel,
			&i.AltLang,
			&i.AltBody,
			&i.CtaLabel,
			&i.CtaTarget,
			&i.Audience,
			&i.PublishAt,
			&i.MediaID,
			&i.MediaKind,
			&i.MediaUrl,
			&i.MediaHlsUrl,
			&i.MediaBytes,
			&i.MediaDurationS,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedLinks = `-- name: ListFeedLinks :many
SELECT target, target_ref, label
FROM feed_links
WHERE item_id = $1
ORDER BY ord
`

type ListFeedLinksRow struct {
	Target    TargetKind
	TargetRef string
	Label     string
}

func (q *Queries) ListFeedLinks(ctx context.Context, itemID uuid.UUID) ([]ListFeedLinksRow, error) {
	rows, err := q.db.Query(ctx, listFeedLinks, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeedLinksRow{}
	for rows.Next() {
		var i ListFeedLinksRow
		if err := rows.Scan(&i.Target, &i.TargetRef, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestPacks = `-- name: ListLatestPacks :many
SELECT DISTINCT ON (slug) slug, lang, version, url, bytes, sha256
FROM packs
WHERE lang = $1
ORDER BY slug, version DESC
`

type ListLatestPacksRow struct {
	Slug    string
	Lang    string
	Version int32
	Url     string
	Bytes   int64
	Sha256  string
}

func (q *Queries) ListLatestPacks(ctx context.Context, lang string) ([]ListLatestPacksRow, error) {
	rows, err := q.db.Query(ctx, listLatestPacks, lang)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLatestPacksRow{}
	for rows.Next() {
		var i ListLatestPacksRow
		if err := rows.Scan(
			&i.Slug,
			&i.Lang,
			&i.Version,
			&i.Url,
			&i.Bytes,
			&i.Sha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ping = `-- name: Ping :one
SELECT 1::int AS ok
`

func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
