// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: library.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getBelief = `-- name: GetBelief :one
SELECT b.n, b.group_key, t.title, t.body
FROM beliefs b
JOIN belief_texts t ON t.n = b.n
WHERE b.n = $1 AND t.lang = $2 AND t.status = 'published'
`

type GetBeliefParams struct {
	N    int32
	Lang string
}

type GetBeliefRow struct {
	N        int32
	GroupKey string
	Title    string
	Body     string
}

func (q *Queries) GetBelief(ctx context.Context, arg GetBeliefParams) (GetBeliefRow, error) {
	row := q.db.QueryRow(ctx, getBelief, arg.N, arg.Lang)
	var i GetBeliefRow
	err := row.Scan(
		&i.N,
		&i.GroupKey,
		&i.Title,
		&i.Body,
	)
	return i, err
}

const getCourseLesson = `-- name: GetCourseLesson :one
SELECT c.id AS course_id, c.title AS course_title,
       (SELECT count(*) FROM course_lessons x WHERE x.course_id = c.id)::int AS total,
       l.id AS lesson_id, l.n, l.title, l.body,
       m.id AS media_id, m.kind AS media_kind, m.url AS media_url, m.hls_url AS media_hls_url,
       m.bytes AS media_bytes, m.duration_s AS media_duration_s
FROM courses c
JOIN course_lessons l ON l.course_id = c.id
LEFT JOIN media m ON m.id = l.image
WHERE c.id = $1 AND l.n = $2 AND c.status = 'published'
`

type GetCourseLessonParams struct {
	CourseID int32
	N        int32
}

type GetCourseLessonRow struct {
	CourseID       int32
	CourseTitle    string
	Total          int32
	LessonID       int32
	N              int32
	Title          string
	Body           string
	MediaID        uuid.NullUUID
	MediaKind      NullMediaKind
	MediaUrl       pgtype.Text
	MediaHlsUrl    pgtype.Text
	MediaBytes     pgtype.Int8
	MediaDurationS pgtype.Int4
}

func (q *Queries) GetCourseLesson(ctx context.Context, arg GetCourseLessonParams) (GetCourseLessonRow, error) {
	row := q.db.QueryRow(ctx, getCourseLesson, arg.CourseID, arg.N)
	var i GetCourseLessonRow
	err := row.Scan(
		&i.CourseID,
		&i.CourseTitle,
		&i.Total,
		&i.LessonID,
		&i.N,
		&i.Title,
		&i.Body,
		&i.MediaID,
		&i.MediaKind,
		&i.MediaUrl,
		&i.MediaHlsUrl,
		&i.MediaBytes,
		&i.MediaDurationS,
	)
	return i, err
}

const getEgwEdition = `-- name: GetEgwEdition :one
SELECT e.id, e.book_code, e.lang, e.title,
       (SELECT count(DISTINCT p.chapter) FROM egw_paragraphs p WHERE p.edition_id = e.id)::int AS chapters
FROM egw_editions e
WHERE e.id = $1
`

type GetEgwEditionRow struct {
	ID       int32
	BookCode string
	Lang     string
	Title    string
	Chapters int32
}

func (q *Queries) GetEgwEdition(ctx context.Context, id int32) (GetEgwEditionRow, error) {
	row := q.db.QueryRow(ctx, getEgwEdition, id)
	var i GetEgwEditionRow
	err := row.Scan(
		&i.ID,
		&i.BookCode,
		&i.Lang,
		&i.Title,
		&i.Chapters,
	)
	return i, err
}

const getEgwEditionByBookLang = `-- name: GetEgwEditionByBookLang :one
SELECT id FROM egw_editions WHERE book_code = $1 AND lang = $2
`

type GetEgwEditionByBookLangParams struct {
	BookCode string
	Lang     string
}

func (q *Queries) GetEgwEditionByBookLang(ctx context.Context, arg GetEgwEditionByBookLangParams) (int32, error) {
	row := q.db.QueryRow(ctx, getEgwEditionByBookLang, arg.BookCode, arg.Lang)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getHymn = `-- name: GetHymn :one
SELECT h.id, h.number, h.title, h.original_title, h.category,
       c.id AS choir_id, c.kind AS choir_kind, c.url AS choir_url, c.hls_url AS choir_hls_url, c.bytes AS choir_bytes, c.duration_s AS choir_duration_s,
       p.id AS piano_id, p.kind AS piano_kind, p.url AS piano_url, p.hls_url AS piano_hls_url, p.bytes AS piano_bytes, p.duration_s AS piano_duration_s
FROM hymns h
LEFT JOIN media c ON c.id = h.audio_choir
LEFT JOIN media p ON p.id = h.audio_piano
WHERE h.hymnal_id = $1 AND h.number = $2
`

type GetHymnParams struct {
	HymnalID int32
	Number   int32
}

type GetHymnRow struct {
	ID             int32
	Number         int32
	Title          string
	OriginalTitle  pgtype.Text
	Category       pgtype.Text
	ChoirID        uuid.NullUUID
	ChoirKind      NullMediaKind
	ChoirUrl       pgtype.Text
	ChoirHlsUrl    pgtype.Text
	ChoirBytes     pgtype.Int8
	ChoirDurationS pgtype.Int4
	PianoID        uuid.NullUUID
	PianoKind      NullMediaKind
	PianoUrl       pgtype.Text
	PianoHlsUrl    pgtype.Text
	PianoBytes     pgtype.Int8
	PianoDurationS pgtype.Int4
}

func (q *Queries) GetHymn(ctx context.Context, arg GetHymnParams) (GetHymnRow, error) {
	row := q.db.QueryRow(ctx, getHymn, arg.HymnalID, arg.Number)
	var i GetHymnRow
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Title,
		&i.OriginalTitle,
		&i.Category,
		&i.ChoirID,
		&i.ChoirKind,
		&i.ChoirUrl,
		&i.ChoirHlsUrl,
		&i.ChoirBytes,
		&i.ChoirDurationS,
		&i.PianoID,
		&i.PianoKind,
		&i.PianoUrl,
		&i.PianoHlsUrl,
		&i.PianoBytes,
		&i.PianoDurationS,
	)
	return i, err
}

const getHymnal = `-- name: GetHymnal :one
SELECT id, code, lang, name FROM hymnals WHERE code = $1
`

type GetHymnalRow struct {
	ID   int32
	Code string
	Lang string
	Name string
}

func (q *Queries) GetHymnal(ctx context.Context, code string) (GetHymnalRow, error) {
	row := q.db.QueryRow(ctx, getHymnal, code)
	var i GetHymnalRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Lang,
		&i.Name,
	)
	return i, err
}

const getSabbathSchoolLesson = `-- name: GetSabbathSchoolLesson :one

SELECT q.year, q.quarter, q.title AS quarter_title,
       l.id AS lesson_id, l.n, l.title, l.week_start, l.memory_ref, l.memory_text
FROM ss_lessons l
JOIN ss_quarters q ON q.id = l.quarter_id
WHERE q.lang = $1 AND q.status = 'published'
  AND l.week_start <= $2::date AND $2::date < l.week_start + 7
ORDER BY l.week_start DESC
LIMIT 1
`

type GetSabbathSchoolLessonParams struct {
	Lang string
	Day  pgtype.Date
}

type GetSabbathSchoolLessonRow struct {
	Year         int32
	Quarter      int32
	QuarterTitle string
	LessonID     int32
	N            int32
	Title        string
	WeekStart    pgtype.Date
	MemoryRef    pgtype.Text
	MemoryText   pgtype.Text
}

// ── Sabbath School ──────────────────────────────────────
func (q *Queries) GetSabbathSchoolLesson(ctx context.Context, arg GetSabbathSchoolLessonParams) (GetSabbathSchoolLessonRow, error) {
	row := q.db.QueryRow(ctx, getSabbathSchoolLesson, arg.Lang, arg.Day)
	var i GetSabbathSchoolLessonRow
	err := row.Scan(
		&i.Year,
		&i.Quarter,
		&i.QuarterTitle,
		&i.LessonID,
		&i.N,
		&i.Title,
		&i.WeekStart,
		&i.MemoryRef,
		&i.MemoryText,
	)
	return i, err
}

const listBeliefs = `-- name: ListBeliefs :many

SELECT b.n, b.group_key, t.title
FROM beliefs b
JOIN belief_texts t ON t.n = b.n
WHERE t.lang = $1 AND t.status = 'published'
ORDER BY b.n
`

type ListBeliefsRow struct {
	N        int32
	GroupKey string
	Title    string
}

// ── Fundamental Beliefs ─────────────────────────────────
func (q *Queries) ListBeliefs(ctx context.Context, lang string) ([]ListBeliefsRow, error) {
	rows, err := q.db.Query(ctx, listBeliefs, lang)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBeliefsRow{}
	for rows.Next() {
		var i ListBeliefsRow
		if err := rows.Scan(&i.N, &i.GroupKey, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourses = `-- name: ListCourses :many

SELECT c.id, c.slug, c.title, c.audience,
       (SELECT count(*) FROM course_lessons cl WHERE cl.course_id = c.id)::int AS lessons
FROM courses c
WHERE c.lang = $1 AND c.status = 'published'
ORDER BY c.title
`

type ListCoursesRow struct {
	ID       int32
	Slug     string
	Title    string
	Audience []string
	Lessons  int32
}

// ── Courses ─────────────────────────────────────────────
func (q *Queries) ListCourses(ctx context.Context, lang string) ([]ListCoursesRow, error) {
	rows, err := q.db.Query(ctx, listCourses, lang)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoursesRow{}
	for rows.Next() {
		var i ListCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Audience,
			&i.Lessons,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEgwBooks = `-- name: ListEgwBooks :many

SELECT e.id, e.book_code, e.lang, e.title, b.original_title,
       (SELECT count(DISTINCT p.chapter) FROM egw_paragraphs p WHERE p.edition_id = e.id)::int AS chapters
FROM egw_editions e
JOIN egw_books b ON b.code = e.book_code
WHERE e.lang = $1
ORDER BY e.title
`

type ListEgwBooksRow struct {
	ID            int32
	BookCode      string
	Lang          string
	Title         string
	OriginalTitle string
	Chapters      int32
}

// ── EGW ─────────────────────────────────────────────────
func (q *Queries) ListEgwBooks(ctx context.Context, lang string) ([]ListEgwBooksRow, error) {
	rows, err := q.db.Query(ctx, listEgwBooks, lang)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEgwBooksRow{}
	for rows.Next() {
		var i ListEgwBooksRow
		if err := rows.Scan(
			&i.ID,
			&i.BookCode,
			&i.Lang,
			&i.Title,
			&i.OriginalTitle,
			&i.Chapters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEgwChapterParagraphs = `-- name: ListEgwChapterParagraphs :many
SELECT refcode, ord, page, text, chapter_title
FROM egw_paragraphs
WHERE edition_id = $1 AND chapter = $2
ORDER BY ord
`

type ListEgwChapterParagraphsParams struct {
	EditionID int32
	Chapter   int32
}

type ListEgwChapterParagraphsRow struct {
	Refcode      string
	Ord          int32
	Page         pgtype.Int4
	Text         string
	ChapterTitle pgtype.Text
}

func (q *Queries) ListEgwChapterParagraphs(ctx context.Context, arg ListEgwChapterParagraphsParams) ([]ListEgwChapterParagraphsRow, error) {
	rows, err := q.db.Query(ctx, listEgwChapterParagraphs, arg.EditionID, arg.Chapter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEgwChapterParagraphsRow{}
	for rows.Next() {
		var i ListEgwChapterParagraphsRow
		if err := rows.Scan(
			&i.Refcode,
			&i.Ord,
			&i.Page,
			&i.Text,
			&i.ChapterTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHymnStanzas = `-- name: ListHymnStanzas :many
SELECT idx, kind, text FROM hymn_stanzas WHERE hymn_id = $1 ORDER BY idx
`

type ListHymnStanzasRow struct {
	Idx  int32
	Kind string
	Text string
}

func (q *Queries) ListHymnStanzas(ctx context.Context, hymnID int32) ([]ListHymnStanzasRow, error) {
	rows, err := q.db.Query(ctx, listHymnStanzas, hymnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHymnStanzasRow{}
	for rows.Next() {
		var i ListHymnStanzasRow
		if err := rows.Scan(&i.Idx, &i.Kind, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHymnals = `-- name: ListHymnals :many

SELECT code, lang, name FROM hymnals ORDER BY lang, code
`

type ListHymnalsRow struct {
	Code string
	Lang string
	Name string
}

// ── Hymnals ─────────────────────────────────────────────
func (q *Queries) ListHymnals(ctx context.Context) ([]ListHymnalsRow, error) {
	rows, err := q.db.Query(ctx, listHymnals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHymnalsRow{}
	for rows.Next() {
		var i ListHymnalsRow
		if err := rows.Scan(&i.Code, &i.Lang, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHymns = `-- name: ListHymns :many
SELECT number, title, original_title, category,
       (audio_choir IS NOT NULL OR audio_piano IS NOT NULL)::bool AS has_audio
FROM hymns
WHERE hymnal_id = $1
  AND ($2::int IS NULL OR number = $2::int)
  AND ($3::text IS NULL
       OR immutable_unaccent(title) ILIKE '%' || immutable_unaccent($3::text) || '%'
       OR similarity(immutable_unaccent(title), immutable_unaccent($3::text)) > 0.3)
ORDER BY number
LIMIT 500
`

type ListHymnsParams struct {
	HymnalID int32
	QNumber  pgtype.Int4
	QTitle   pgtype.Text
}

type ListHymnsRow struct {
	Number        int32
	Title         string
	OriginalTitle pgtype.Text
	Category      pgtype.Text
	HasAudio      bool
}

// q_number filters by exact number; q_title by accent-folded substring or trigram similarity.
func (q *Queries) ListHymns(ctx context.Context, arg ListHymnsParams) ([]ListHymnsRow, error) {
	rows, err := q.db.Query(ctx, listHymns, arg.HymnalID, arg.QNumber, arg.QTitle)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHymnsRow{}
	for rows.Next() {
		var i ListHymnsRow
		if err := rows.Scan(
			&i.Number,
			&i.Title,
			&i.OriginalTitle,
			&i.Category,
			&i.HasAudio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLessonOptions = `-- name: ListLessonOptions :many
SELECT o.id, o.question_id, o.label, o.is_correct
FROM quiz_options o
JOIN quiz_questions q ON q.id = o.question_id
WHERE q.lesson_id = $1
ORDER BY o.question_id, o.ord
`

type ListLessonOptionsRow struct {
	ID         int32
	QuestionID int32
	Label      string
	IsCorrect  bool
}

func (q *Queries) ListLessonOptions(ctx context.Context, lessonID int32) ([]ListLessonOptionsRow, error) {
	rows, err := q.db.Query(ctx, listLessonOptions, lessonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLessonOptionsRow{}
	for rows.Next() {
		var i ListLessonOptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Label,
			&i.IsCorrect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLessonQuestions = `-- name: ListLessonQuestions :many
SELECT id, prompt, explain_ref, explain_text FROM quiz_questions WHERE lesson_id = $1 ORDER BY id
`

type ListLessonQuestionsRow struct {
	ID          int32
	Prompt      string
	ExplainRef  pgtype.Text
	ExplainText pgtype.Text
}

func (q *Queries) ListLessonQuestions(ctx context.Context, lessonID int32) ([]ListLessonQuestionsRow, error) {
	rows, err := q.db.Query(ctx, listLessonQuestions, lessonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLessonQuestionsRow{}
	for rows.Next() {
		var i ListLessonQuestionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Prompt,
			&i.ExplainRef,
			&i.ExplainText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSabbathSchoolDays = `-- name: ListSabbathSchoolDays :many
SELECT d.day_idx, d.title, d.body, d.question,
       m.id AS media_id, m.kind AS media_kind, m.url AS media_url, m.hls_url AS media_hls_url,
       m.bytes AS media_bytes, m.duration_s AS media_duration_s
FROM ss_days d
LEFT JOIN media m ON m.id = d.audio
WHERE d.lesson_id = $1
ORDER BY d.day_idx
`

type ListSabbathSchoolDaysRow struct {
	DayIdx         int32
	Title          string
	Body           string
	Question       pgtype.Text
	MediaID        uuid.NullUUID
	MediaKind      NullMediaKind
	MediaUrl       pgtype.Text
	MediaHlsUrl    pgtype.Text
	MediaBytes     pgtype.Int8
	MediaDurationS pgtype.Int4
}

func (q *Queries) ListSabbathSchoolDays(ctx context.Context, lessonID int32) ([]ListSabbathSchoolDaysRow, error) {
	rows, err := q.db.Query(ctx, listSabbathSchoolDays, lessonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSabbathSchoolDaysRow{}
	for rows.Next() {
		var i ListSabbathSchoolDaysRow
		if err := rows.Scan(
			&i.DayIdx,
			&i.Title,
			&i.Body,
			&i.Question,
			&i.MediaID,
			&i.MediaKind,
			&i.MediaUrl,
			&i.MediaHlsUrl,
			&i.MediaBytes,
			&i.MediaDurationS,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
