// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ContentStatus string

const (
	ContentStatusDraft     ContentStatus = "draft"
	ContentStatusInReview  ContentStatus = "in_review"
	ContentStatusApproved  ContentStatus = "approved"
	ContentStatusPublished ContentStatus = "published"
	ContentStatusRejected  ContentStatus = "rejected"
)

func (e *ContentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContentStatus(s)
	case string:
		*e = ContentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ContentStatus: %T", src)
	}
	return nil
}

type NullContentStatus struct {
	ContentStatus ContentStatus
	Valid         bool // Valid is true if ContentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ContentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContentStatus), nil
}

func (e ContentStatus) Valid() bool {
	switch e {
	case ContentStatusDraft,
		ContentStatusInReview,
		ContentStatusApproved,
		ContentStatusPublished,
		ContentStatusRejected:
		return true
	}
	return false
}

type FeedKind string

const (
	FeedKindVerse         FeedKind = "verse"
	FeedKindEgwQuote      FeedKind = "egw_quote"
	FeedKindSabbathSchool FeedKind = "sabbath_school"
	FeedKindProphecy      FeedKind = "prophecy"
	FeedKindHymn          FeedKind = "hymn"
	FeedKindHealth        FeedKind = "health"
	FeedKindYouth         FeedKind = "youth"
	FeedKindDevotional    FeedKind = "devotional"
	FeedKindSermon        FeedKind = "sermon"
	FeedKindAudioBible    FeedKind = "audio_bible"
)

func (e *FeedKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FeedKind(s)
	case string:
		*e = FeedKind(s)
	default:
		return fmt.Errorf("unsupported scan type for FeedKind: %T", src)
	}
	return nil
}

type NullFeedKind struct {
	FeedKind FeedKind
	Valid    bool // Valid is true if FeedKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFeedKind) Scan(value interface{}) error {
	if value == nil {
		ns.FeedKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FeedKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFeedKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FeedKind), nil
}

func (e FeedKind) Valid() bool {
	switch e {
	case FeedKindVerse,
		FeedKindEgwQuote,
		FeedKindSabbathSchool,
		FeedKindProphecy,
		FeedKindHymn,
		FeedKindHealth,
		FeedKindYouth,
		FeedKindDevotional,
		FeedKindSermon,
		FeedKindAudioBible:
		return true
	}
	return false
}

type MediaKind string

const (
	MediaKindVideo MediaKind = "video"
	MediaKindAudio MediaKind = "audio"
	MediaKindImage MediaKind = "image"
)

func (e *MediaKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MediaKind(s)
	case string:
		*e = MediaKind(s)
	default:
		return fmt.Errorf("unsupported scan type for MediaKind: %T", src)
	}
	return nil
}

type NullMediaKind struct {
	MediaKind MediaKind
	Valid     bool // Valid is true if MediaKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMediaKind) Scan(value interface{}) error {
	if value == nil {
		ns.MediaKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MediaKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMediaKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MediaKind), nil
}

func (e MediaKind) Valid() bool {
	switch e {
	case MediaKindVideo,
		MediaKindAudio,
		MediaKindImage:
		return true
	}
	return false
}

type TargetKind string

const (
	TargetKindVerse        TargetKind = "verse"
	TargetKindEgwParagraph TargetKind = "egw_paragraph"
	TargetKindBelief       TargetKind = "belief"
	TargetKindHymn         TargetKind = "hymn"
	TargetKindFeedItem     TargetKind = "feed_item"
	TargetKindSsDay        TargetKind = "ss_day"
	TargetKindCourseLesson TargetKind = "course_lesson"
)

func (e *TargetKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TargetKind(s)
	case string:
		*e = TargetKind(s)
	default:
		return fmt.Errorf("unsupported scan type for TargetKind: %T", src)
	}
	return nil
}

type NullTargetKind struct {
	TargetKind TargetKind
	Valid      bool // Valid is true if TargetKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTargetKind) Scan(value interface{}) error {
	if value == nil {
		ns.TargetKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TargetKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTargetKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TargetKind), nil
}

func (e TargetKind) Valid() bool {
	switch e {
	case TargetKindVerse,
		TargetKindEgwParagraph,
		TargetKindBelief,
		TargetKindHymn,
		TargetKindFeedItem,
		TargetKindSsDay,
		TargetKindCourseLesson:
		return true
	}
	return false
}

type UserRole string

const (
	UserRoleMember   UserRole = "member"
	UserRoleEditor   UserRole = "editor"
	UserRoleReviewer UserRole = "reviewer"
	UserRoleAdmin    UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

func (e UserRole) Valid() bool {
	switch e {
	case UserRoleMember,
		UserRoleEditor,
		UserRoleReviewer,
		UserRoleAdmin:
		return true
	}
	return false
}

type Belief struct {
	N        int32
	GroupKey string
}

type BeliefText struct {
	N      int32
	Lang   string
	Title  string
	Body   string
	Status ContentStatus
}

type BibleBook struct {
	Osis      string
	Ord       int32
	Testament string
}

type BibleBookName struct {
	Book string
	Lang string
	Name string
	Abbr string
}

type BibleTranslation struct {
	ID            int32
	Code          string
	Lang          string
	Name          string
	License       string
	Versification string
	Version       int32
}

type Course struct {
	ID       int32
	Slug     string
	Lang     string
	Title    string
	Audience []string
	Status   ContentStatus
}

type CourseLesson struct {
	ID       int32
	CourseID int32
	N        int32
	Title    string
	Body     string
	Image    uuid.NullUUID
}

type EgwBook struct {
	Code          string
	OriginalTitle string
}

type EgwEdition struct {
	ID       int32
	BookCode string
	Lang     string
	Title    string
	License  string
	Version  int32
}

type EgwParagraph struct {
	EditionID    int32
	Refcode      string
	Chapter      int32
	ChapterTitle pgtype.Text
	Ord          int32
	Page         pgtype.Int4
	Text         string
	Tsv          interface{}
}

type FeedItem struct {
	ID        uuid.UUID
	Kind      FeedKind
	Lang      string
	Kicker    string
	Source    pgtype.Text
	Body      string
	RefLabel  pgtype.Text
	AltLang   pgtype.Text
	AltBody   pgtype.Text
	MediaID   uuid.NullUUID
	CtaLabel  pgtype.Text
	CtaTarget pgtype.Text
	Audience  []string
	Status    ContentStatus
	PublishAt pgtype.Timestamptz
	CreatedBy uuid.NullUUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type FeedLink struct {
	ItemID    uuid.UUID
	Ord       int32
	Target    TargetKind
	TargetRef string
	Label     string
}

type Hymn struct {
	ID            int32
	HymnalID      int32
	Number        int32
	Title         string
	OriginalTitle pgtype.Text
	Category      pgtype.Text
	AudioChoir    uuid.NullUUID
	AudioPiano    uuid.NullUUID
}

type HymnStanza struct {
	HymnID int32
	Idx    int32
	Kind   string
	Text   string
}

type Hymnal struct {
	ID      int32
	Code    string
	Lang    string
	Name    string
	License string
}

type Language struct {
	Code string
	Name string
}

type Medium struct {
	ID        uuid.UUID
	Kind      MediaKind
	Url       string
	HlsUrl    pgtype.Text
	Bytes     pgtype.Int8
	DurationS pgtype.Int4
	CreatedAt time.Time
}

type Pack struct {
	ID        int32
	Slug      string
	Lang      string
	Version   int32
	Url       string
	Bytes     int64
	Sha256    string
	CreatedAt time.Time
}

type QuizOption struct {
	ID         int32
	QuestionID int32
	Label      string
	IsCorrect  bool
	Ord        int32
}

type QuizQuestion struct {
	ID          int32
	LessonID    int32
	Prompt      string
	ExplainRef  pgtype.Text
	ExplainText pgtype.Text
}

type Review struct {
	ID           uuid.UUID
	SubjectTable string
	SubjectID    string
	ReviewerID   uuid.UUID
	Decision     ContentStatus
	Note         pgtype.Text
	CreatedAt    time.Time
}

type SsDay struct {
	ID       int32
	LessonID int32
	DayIdx   int32
	Title    string
	Body     string
	Question pgtype.Text
	Audio    uuid.NullUUID
}

type SsLesson struct {
	ID         int32
	QuarterID  int32
	N          int32
	Title      string
	WeekStart  pgtype.Date
	MemoryRef  pgtype.Text
	MemoryText pgtype.Text
}

type SsQuarter struct {
	ID      int32
	Year    int32
	Quarter int32
	Lang    string
	Title   string
	Status  ContentStatus
}

type User struct {
	ID               uuid.UUID
	Phone            pgtype.Text
	DisplayName      pgtype.Text
	Church           pgtype.Text
	Role             UserRole
	Conference       pgtype.Text
	UiLang           string
	ParallelLang     pgtype.Text
	BibleTranslation string
	TextScale        pgtype.Numeric
	DataSaver        bool
	SunsetCity       pgtype.Text
	SunsetLat        pgtype.Numeric
	SunsetLng        pgtype.Numeric
	CreatedAt        time.Time
}

type UserAnswer struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Target    TargetKind
	TargetRef string
	Answer    pgtype.Text
	OptionID  pgtype.Int4
	UpdatedAt time.Time
	DeletedAt pgtype.Timestamptz
}

type UserMark struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Kind      string
	Target    TargetKind
	TargetRef string
	Color     pgtype.Text
	Note      pgtype.Text
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt pgtype.Timestamptz
}

type UserProgress struct {
	UserID    uuid.UUID
	Target    TargetKind
	TargetRef string
	Position  pgtype.Text
	Percent   pgtype.Int4
	UpdatedAt time.Time
}

type Verse struct {
	TranslationID int32
	OsisRef       string
	Book          string
	Chapter       int32
	Verse         int32
	Text          string
	Tsv           interface{}
}
