// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: packs.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertPack = `-- name: InsertPack :exec
INSERT INTO packs (slug, lang, version, url, bytes, sha256, content_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertPackParams struct {
	Slug        string
	Lang        string
	Version     int32
	Url         string
	Bytes       int64
	Sha256      string
	ContentHash pgtype.Text
}

func (q *Queries) InsertPack(ctx context.Context, arg InsertPackParams) error {
	_, err := q.db.Exec(ctx, insertPack,
		arg.Slug,
		arg.Lang,
		arg.Version,
		arg.Url,
		arg.Bytes,
		arg.Sha256,
		arg.ContentHash,
	)
	return err
}

const latestPack = `-- name: LatestPack :one
SELECT id, version, url, bytes, sha256, content_hash
FROM packs
WHERE slug = $1
ORDER BY version DESC
LIMIT 1
`

type LatestPackRow struct {
	ID          int32
	Version     int32
	Url         string
	Bytes       int64
	Sha256      string
	ContentHash pgtype.Text
}

func (q *Queries) LatestPack(ctx context.Context, slug string) (LatestPackRow, error) {
	row := q.db.QueryRow(ctx, latestPack, slug)
	var i LatestPackRow
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Url,
		&i.Bytes,
		&i.Sha256,
		&i.ContentHash,
	)
	return i, err
}

const listEgwEditionsForPacks = `-- name: ListEgwEditionsForPacks :many
SELECT e.id, e.book_code, e.lang, e.title, b.original_title
FROM egw_editions e
JOIN egw_books b ON b.code = e.book_code
ORDER BY e.lang, e.book_code
`

type ListEgwEditionsForPacksRow struct {
	ID            int32
	BookCode      string
	Lang          string
	Title         string
	OriginalTitle string
}

func (q *Queries) ListEgwEditionsForPacks(ctx context.Context) ([]ListEgwEditionsForPacksRow, error) {
	rows, err := q.db.Query(ctx, listEgwEditionsForPacks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEgwEditionsForPacksRow{}
	for rows.Next() {
		var i ListEgwEditionsForPacksRow
		if err := rows.Scan(
			&i.ID,
			&i.BookCode,
			&i.Lang,
			&i.Title,
			&i.OriginalTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEgwParagraphsForPack = `-- name: ListEgwParagraphsForPack :many
SELECT refcode, chapter, chapter_title, ord, page, text
FROM egw_paragraphs
WHERE edition_id = $1
ORDER BY chapter, ord
`

type ListEgwParagraphsForPackRow struct {
	Refcode      string
	Chapter      int32
	ChapterTitle pgtype.Text
	Ord          int32
	Page         pgtype.Int4
	Text         string
}

func (q *Queries) ListEgwParagraphsForPack(ctx context.Context, editionID int32) ([]ListEgwParagraphsForPackRow, error) {
	rows, err := q.db.Query(ctx, listEgwParagraphsForPack, editionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEgwParagraphsForPackRow{}
	for rows.Next() {
		var i ListEgwParagraphsForPackRow
		if err := rows.Scan(
			&i.Refcode,
			&i.Chapter,
			&i.ChapterTitle,
			&i.Ord,
			&i.Page,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHymnalsForPacks = `-- name: ListHymnalsForPacks :many
SELECT id, code, lang, name FROM hymnals ORDER BY code
`

type ListHymnalsForPacksRow struct {
	ID   int32
	Code string
	Lang string
	Name string
}

func (q *Queries) ListHymnalsForPacks(ctx context.Context) ([]ListHymnalsForPacksRow, error) {
	rows, err := q.db.Query(ctx, listHymnalsForPacks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHymnalsForPacksRow{}
	for rows.Next() {
		var i ListHymnalsForPacksRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Lang,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHymnsForPack = `-- name: ListHymnsForPack :many
SELECT number, title, original_title, category
FROM hymns
WHERE hymnal_id = $1
ORDER BY number
`

type ListHymnsForPackRow struct {
	Number        int32
	Title         string
	OriginalTitle pgtype.Text
	Category      pgtype.Text
}

func (q *Queries) ListHymnsForPack(ctx context.Context, hymnalID int32) ([]ListHymnsForPackRow, error) {
	rows, err := q.db.Query(ctx, listHymnsForPack, hymnalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHymnsForPackRow{}
	for rows.Next() {
		var i ListHymnsForPackRow
		if err := rows.Scan(
			&i.Number,
			&i.Title,
			&i.OriginalTitle,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStanzasForPack = `-- name: ListStanzasForPack :many
SELECT h.number, s.idx, s.kind, s.text
FROM hymn_stanzas s
JOIN hymns h ON h.id = s.hymn_id
WHERE h.hymnal_id = $1
ORDER BY h.number, s.idx
`

type ListStanzasForPackRow struct {
	Number int32
	Idx    int32
	Kind   string
	Text   string
}

func (q *Queries) ListStanzasForPack(ctx context.Context, hymnalID int32) ([]ListStanzasForPackRow, error) {
	rows, err := q.db.Query(ctx, listStanzasForPack, hymnalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStanzasForPackRow{}
	for rows.Next() {
		var i ListStanzasForPackRow
		if err := rows.Scan(
			&i.Number,
			&i.Idx,
			&i.Kind,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranslationsForPacks = `-- name: ListTranslationsForPacks :many

SELECT id, code, lang FROM bible_translations ORDER BY code
`

type ListTranslationsForPacksRow struct {
	ID   int32
	Code string
	Lang string
}

// Offline pack builder (cmd/packs). Reads published sources, records built packs.
func (q *Queries) ListTranslationsForPacks(ctx context.Context) ([]ListTranslationsForPacksRow, error) {
	rows, err := q.db.Query(ctx, listTranslationsForPacks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTranslationsForPacksRow{}
	for rows.Next() {
		var i ListTranslationsForPacksRow
		if err := rows.Scan(&i.ID, &i.Code, &i.Lang); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersesForPack = `-- name: ListVersesForPack :many
SELECT osis_ref, book, chapter, verse, text
FROM verses
WHERE translation_id = $1
ORDER BY book, chapter, verse
`

type ListVersesForPackRow struct {
	OsisRef string
	Book    string
	Chapter int32
	Verse   int32
	Text    string
}

func (q *Queries) ListVersesForPack(ctx context.Context, translationID int32) ([]ListVersesForPackRow, error) {
	rows, err := q.db.Query(ctx, listVersesForPack, translationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVersesForPackRow{}
	for rows.Next() {
		var i ListVersesForPackRow
		if err := rows.Scan(
			&i.OsisRef,
			&i.Book,
			&i.Chapter,
			&i.Verse,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePackFile = `-- name: UpdatePackFile :exec
UPDATE packs SET url = $1, bytes = $2, sha256 = $3 WHERE id = $4
`

type UpdatePackFileParams struct {
	Url    string
	Bytes  int64
	Sha256 string
	ID     int32
}

// Same content rebuilt (e.g. file lost on disk): refresh the file facts for the existing version.
func (q *Queries) UpdatePackFile(ctx context.Context, arg UpdatePackFileParams) error {
	_, err := q.db.Exec(ctx, updatePackFile,
		arg.Url,
		arg.Bytes,
		arg.Sha256,
		arg.ID,
	)
	return err
}
