// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const findBookByName = `-- name: FindBookByName :one
SELECT book FROM bible_book_names
WHERE lower(immutable_unaccent(name)) = lower(immutable_unaccent($1)) OR lower(abbr) = lower($1)
ORDER BY (lang = $2) DESC
LIMIT 1
`

type FindBookByNameParams struct {
	Name string
	Lang string
}

func (q *Queries) FindBookByName(ctx context.Context, arg FindBookByNameParams) (string, error) {
	row := q.db.QueryRow(ctx, findBookByName, arg.Name, arg.Lang)
	var book string
	err := row.Scan(&book)
	return book, err
}

const getVerseInLang = `-- name: GetVerseInLang :one
SELECT v.osis_ref, v.text, n.name AS book_name
FROM verses v
JOIN bible_translations t ON t.id = v.translation_id
LEFT JOIN bible_book_names n ON n.book = v.book AND n.lang = t.lang
WHERE t.lang = $1 AND v.book = $2 AND v.chapter = $3 AND v.verse = $4
ORDER BY t.id
LIMIT 1
`

type GetVerseInLangParams struct {
	Lang    string
	Book    string
	Chapter int32
	Verse   int32
}

type GetVerseInLangRow struct {
	OsisRef  string
	Text     string
	BookName pgtype.Text
}

func (q *Queries) GetVerseInLang(ctx context.Context, arg GetVerseInLangParams) (GetVerseInLangRow, error) {
	row := q.db.QueryRow(ctx, getVerseInLang,
		arg.Lang,
		arg.Book,
		arg.Chapter,
		arg.Verse,
	)
	var i GetVerseInLangRow
	err := row.Scan(&i.OsisRef, &i.Text, &i.BookName)
	return i, err
}

const searchBeliefs = `-- name: SearchBeliefs :many
SELECT t.n, t.title, t.body
FROM belief_texts t
WHERE t.lang = $1 AND t.status = 'published'
  AND (immutable_unaccent(t.title) ILIKE '%' || immutable_unaccent($2) || '%'
       OR immutable_unaccent(t.body) ILIKE '%' || immutable_unaccent($2) || '%'
       OR similarity(immutable_unaccent(t.title), immutable_unaccent($2)) > 0.3)
ORDER BY similarity(immutable_unaccent(t.title), immutable_unaccent($2)) DESC, t.n
LIMIT $3
`

type SearchBeliefsParams struct {
	Lang string
	Q    string
	Lim  int32
}

type SearchBeliefsRow struct {
	N     int32
	Title string
	Body  string
}

func (q *Queries) SearchBeliefs(ctx context.Context, arg SearchBeliefsParams) ([]SearchBeliefsRow, error) {
	rows, err := q.db.Query(ctx, searchBeliefs, arg.Lang, arg.Q, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchBeliefsRow{}
	for rows.Next() {
		var i SearchBeliefsRow
		if err := rows.Scan(&i.N, &i.Title, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchEgw = `-- name: SearchEgw :many
SELECT p.refcode, p.text, p.chapter, e.id AS edition_id, e.title
FROM egw_paragraphs p
JOIN egw_editions e ON e.id = p.edition_id
WHERE e.lang = $1
  AND (p.tsv @@ plainto_tsquery('simple', $2)
       OR immutable_unaccent(p.text) ILIKE '%' || immutable_unaccent($2) || '%')
ORDER BY ts_rank(p.tsv, plainto_tsquery('simple', $2)) DESC, e.id, p.chapter, p.ord
LIMIT $3
`

type SearchEgwParams struct {
	Lang string
	Q    string
	Lim  int32
}

type SearchEgwRow struct {
	Refcode   string
	Text      string
	Chapter   int32
	EditionID int32
	Title     string
}

func (q *Queries) SearchEgw(ctx context.Context, arg SearchEgwParams) ([]SearchEgwRow, error) {
	rows, err := q.db.Query(ctx, searchEgw, arg.Lang, arg.Q, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchEgwRow{}
	for rows.Next() {
		var i SearchEgwRow
		if err := rows.Scan(
			&i.Refcode,
			&i.Text,
			&i.Chapter,
			&i.EditionID,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchHymns = `-- name: SearchHymns :many
SELECT h.number, h.title, h.category, y.code
FROM hymns h
JOIN hymnals y ON y.id = h.hymnal_id
WHERE y.lang = $1
  AND (h.number::text = $2::text
       OR immutable_unaccent(h.title) ILIKE '%' || immutable_unaccent($2::text) || '%'
       OR similarity(immutable_unaccent(h.title), immutable_unaccent($2::text)) > 0.3)
ORDER BY (h.number::text = $2::text) DESC, similarity(immutable_unaccent(h.title), immutable_unaccent($2::text)) DESC, h.number
LIMIT $3
`

type SearchHymnsParams struct {
	Lang string
	Q    string
	Lim  int32
}

type SearchHymnsRow struct {
	Number   int32
	Title    string
	Category pgtype.Text
	Code     string
}

func (q *Queries) SearchHymns(ctx context.Context, arg SearchHymnsParams) ([]SearchHymnsRow, error) {
	rows, err := q.db.Query(ctx, searchHymns, arg.Lang, arg.Q, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchHymnsRow{}
	for rows.Next() {
		var i SearchHymnsRow
		if err := rows.Scan(
			&i.Number,
			&i.Title,
			&i.Category,
			&i.Code,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchVerses = `-- name: SearchVerses :many

SELECT v.osis_ref, v.book, v.chapter, v.verse, v.text, n.name AS book_name
FROM verses v
JOIN bible_translations t ON t.id = v.translation_id
LEFT JOIN bible_book_names n ON n.book = v.book AND n.lang = t.lang
WHERE t.lang = $1
  AND (v.tsv @@ plainto_tsquery('simple', $2)
       OR immutable_unaccent(v.text) ILIKE '%' || immutable_unaccent($2) || '%')
ORDER BY ts_rank(v.tsv, plainto_tsquery('simple', $2)) DESC, t.id, v.book, v.chapter, v.verse
LIMIT $3
`

type SearchVersesParams struct {
	Lang string
	Q    string
	Lim  int32
}

type SearchVersesRow struct {
	OsisRef  string
	Book     string
	Chapter  int32
	Verse    int32
	Text     string
	BookName pgtype.Text
}

// Grouped search. `q` is the raw query; matching is accent-folded (immutable_unaccent) substring, full-text
// (`simple` config — Postgres has no Swahili stemmer) and trigram similarity.
func (q *Queries) SearchVerses(ctx context.Context, arg SearchVersesParams) ([]SearchVersesRow, error) {
	rows, err := q.db.Query(ctx, searchVerses, arg.Lang, arg.Q, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchVersesRow{}
	for rows.Next() {
		var i SearchVersesRow
		if err := rows.Scan(
			&i.OsisRef,
			&i.Book,
			&i.Chapter,
			&i.Verse,
			&i.Text,
			&i.BookName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchVideos = `-- name: SearchVideos :many
SELECT f.id, f.kicker, f.body, f.ref_label
FROM feed_items f
JOIN media m ON m.id = f.media_id AND m.kind = 'video'
WHERE f.lang = $1 AND f.status = 'published' AND f.publish_at <= now()
  AND f.kind IN ('prophecy', 'sermon')
  AND (immutable_unaccent(f.body) ILIKE '%' || immutable_unaccent($2) || '%'
       OR immutable_unaccent(f.kicker) ILIKE '%' || immutable_unaccent($2) || '%'
       OR immutable_unaccent(coalesce(f.ref_label, '')) ILIKE '%' || immutable_unaccent($2) || '%')
ORDER BY f.publish_at DESC
LIMIT $3
`

type SearchVideosParams struct {
	Lang string
	Q    string
	Lim  int32
}

type SearchVideosRow struct {
	ID       uuid.UUID
	Kicker   string
	Body     string
	RefLabel pgtype.Text
}

func (q *Queries) SearchVideos(ctx context.Context, arg SearchVideosParams) ([]SearchVideosRow, error) {
	rows, err := q.db.Query(ctx, searchVideos, arg.Lang, arg.Q, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchVideosRow{}
	for rows.Next() {
		var i SearchVideosRow
		if err := rows.Scan(
			&i.ID,
			&i.Kicker,
			&i.Body,
			&i.RefLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
