// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countLikes = `-- name: CountLikes :one
SELECT count(DISTINCT user_id)::int FROM user_marks
WHERE kind = 'like' AND target = 'feed_item' AND target_ref = $1 AND deleted_at IS NULL
`

func (q *Queries) CountLikes(ctx context.Context, targetRef string) (int32, error) {
	row := q.db.QueryRow(ctx, countLikes, targetRef)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteLikes = `-- name: DeleteLikes :exec
UPDATE user_marks SET deleted_at = now(), updated_at = now(), server_updated_at = now()
WHERE user_id = $1 AND kind = 'like' AND target = 'feed_item' AND target_ref = $2 AND deleted_at IS NULL
`

type DeleteLikesParams struct {
	UserID    uuid.UUID
	TargetRef string
}

func (q *Queries) DeleteLikes(ctx context.Context, arg DeleteLikesParams) error {
	_, err := q.db.Exec(ctx, deleteLikes, arg.UserID, arg.TargetRef)
	return err
}

const feedItemPublished = `-- name: FeedItemPublished :one
SELECT EXISTS (SELECT 1 FROM feed_items WHERE id = $1 AND status = 'published' AND publish_at <= now())
`

func (q *Queries) FeedItemPublished(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, feedItemPublished, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getQuizOptionForLesson = `-- name: GetQuizOptionForLesson :one

SELECT o.is_correct,
       (SELECT c.id FROM quiz_options c WHERE c.question_id = q.id AND c.is_correct ORDER BY c.ord LIMIT 1)::int AS correct_option_id
FROM quiz_options o
JOIN quiz_questions q ON q.id = o.question_id
JOIN course_lessons l ON l.id = q.lesson_id
JOIN courses c ON c.id = l.course_id
WHERE o.id = $1 AND q.id = $2 AND l.course_id = $3 AND l.n = $4 AND c.status = 'published'
`

type GetQuizOptionForLessonParams struct {
	OptionID   int32
	QuestionID int32
	CourseID   int32
	N          int32
}

type GetQuizOptionForLessonRow struct {
	IsCorrect       bool
	CorrectOptionID int32
}

// ── Quiz answers ────────────────────────────────────────
// Confirms option ∈ question ∈ lesson ∈ published course, and returns the correct option of that question.
func (q *Queries) GetQuizOptionForLesson(ctx context.Context, arg GetQuizOptionForLessonParams) (GetQuizOptionForLessonRow, error) {
	row := q.db.QueryRow(ctx, getQuizOptionForLesson,
		arg.OptionID,
		arg.QuestionID,
		arg.CourseID,
		arg.N,
	)
	var i GetQuizOptionForLessonRow
	err := row.Scan(&i.IsCorrect, &i.CorrectOptionID)
	return i, err
}

const hasActiveLike = `-- name: HasActiveLike :one

SELECT EXISTS (
  SELECT 1 FROM user_marks
  WHERE user_id = $1 AND kind = 'like' AND target = 'feed_item' AND target_ref = $2 AND deleted_at IS NULL
)
`

type HasActiveLikeParams struct {
	UserID    uuid.UUID
	TargetRef string
}

// ── Likes ───────────────────────────────────────────────
func (q *Queries) HasActiveLike(ctx context.Context, arg HasActiveLikeParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveLike, arg.UserID, arg.TargetRef)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertLike = `-- name: InsertLike :exec
INSERT INTO user_marks (id, user_id, kind, target, target_ref, created_at, updated_at)
VALUES (gen_random_uuid(), $1, 'like', 'feed_item', $2, now(), now())
`

type InsertLikeParams struct {
	UserID    uuid.UUID
	TargetRef string
}

func (q *Queries) InsertLike(ctx context.Context, arg InsertLikeParams) error {
	_, err := q.db.Exec(ctx, insertLike, arg.UserID, arg.TargetRef)
	return err
}

const insertQuizAnswer = `-- name: InsertQuizAnswer :exec
INSERT INTO user_answers (id, user_id, target, target_ref, option_id, updated_at)
VALUES (gen_random_uuid(), $1, 'course_lesson', $2, $3, now())
`

type InsertQuizAnswerParams struct {
	UserID    uuid.UUID
	TargetRef string
	OptionID  pgtype.Int4
}

func (q *Queries) InsertQuizAnswer(ctx context.Context, arg InsertQuizAnswerParams) error {
	_, err := q.db.Exec(ctx, insertQuizAnswer, arg.UserID, arg.TargetRef, arg.OptionID)
	return err
}

const pullAnswers = `-- name: PullAnswers :many
SELECT id, target, target_ref, answer, option_id, updated_at, deleted_at
FROM user_answers
WHERE user_id = $1 AND ($2::timestamptz IS NULL OR server_updated_at > $2::timestamptz)
ORDER BY server_updated_at
`

type PullAnswersParams struct {
	UserID uuid.UUID
	Since  pgtype.Timestamptz
}

type PullAnswersRow struct {
	ID        uuid.UUID
	Target    TargetKind
	TargetRef string
	Answer    pgtype.Text
	OptionID  pgtype.Int4
	UpdatedAt time.Time
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) PullAnswers(ctx context.Context, arg PullAnswersParams) ([]PullAnswersRow, error) {
	rows, err := q.db.Query(ctx, pullAnswers, arg.UserID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PullAnswersRow{}
	for rows.Next() {
		var i PullAnswersRow
		if err := rows.Scan(
			&i.ID,
			&i.Target,
			&i.TargetRef,
			&i.Answer,
			&i.OptionID,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pullMarks = `-- name: PullMarks :many
SELECT id, kind, target, target_ref, color, note, created_at, updated_at, deleted_at
FROM user_marks
WHERE user_id = $1 AND ($2::timestamptz IS NULL OR server_updated_at > $2::timestamptz)
ORDER BY server_updated_at
`

type PullMarksParams struct {
	UserID uuid.UUID
	Since  pgtype.Timestamptz
}

type PullMarksRow struct {
	ID        uuid.UUID
	Kind      string
	Target    TargetKind
	TargetRef string
	Color     pgtype.Text
	Note      pgtype.Text
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) PullMarks(ctx context.Context, arg PullMarksParams) ([]PullMarksRow, error) {
	rows, err := q.db.Query(ctx, pullMarks, arg.UserID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PullMarksRow{}
	for rows.Next() {
		var i PullMarksRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Target,
			&i.TargetRef,
			&i.Color,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pullProgress = `-- name: PullProgress :many
SELECT target, target_ref, position, percent, updated_at
FROM user_progress
WHERE user_id = $1 AND ($2::timestamptz IS NULL OR server_updated_at > $2::timestamptz)
ORDER BY server_updated_at
`

type PullProgressParams struct {
	UserID uuid.UUID
	Since  pgtype.Timestamptz
}

type PullProgressRow struct {
	Target    TargetKind
	TargetRef string
	Position  pgtype.Text
	Percent   pgtype.Int4
	UpdatedAt time.Time
}

func (q *Queries) PullProgress(ctx context.Context, arg PullProgressParams) ([]PullProgressRow, error) {
	rows, err := q.db.Query(ctx, pullProgress, arg.UserID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PullProgressRow{}
	for rows.Next() {
		var i PullProgressRow
		if err := rows.Scan(
			&i.Target,
			&i.TargetRef,
			&i.Position,
			&i.Percent,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncNow = `-- name: SyncNow :one

SELECT now()::timestamptz AS now
`

// ── Sync pull ───────────────────────────────────────────
func (q *Queries) SyncNow(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, syncNow)
	var now time.Time
	err := row.Scan(&now)
	return now, err
}

const updateQuizAnswer = `-- name: UpdateQuizAnswer :execrows
UPDATE user_answers SET option_id = $1, answer = NULL, deleted_at = NULL, updated_at = now(), server_updated_at = now()
WHERE user_id = $2 AND target = 'course_lesson' AND target_ref = $3
`

type UpdateQuizAnswerParams struct {
	OptionID  pgtype.Int4
	UserID    uuid.UUID
	TargetRef string
}

func (q *Queries) UpdateQuizAnswer(ctx context.Context, arg UpdateQuizAnswerParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateQuizAnswer, arg.OptionID, arg.UserID, arg.TargetRef)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertAnswer = `-- name: UpsertAnswer :exec
INSERT INTO user_answers (id, user_id, target, target_ref, answer, option_id, updated_at, deleted_at, server_updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now())
ON CONFLICT (id) DO UPDATE
SET target = EXCLUDED.target, target_ref = EXCLUDED.target_ref, answer = EXCLUDED.answer, option_id = EXCLUDED.option_id,
    updated_at = EXCLUDED.updated_at, deleted_at = EXCLUDED.deleted_at, server_updated_at = now()
WHERE user_answers.user_id = EXCLUDED.user_id AND EXCLUDED.updated_at > user_answers.updated_at
`

type UpsertAnswerParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Target    TargetKind
	TargetRef string
	Answer    pgtype.Text
	OptionID  pgtype.Int4
	UpdatedAt time.Time
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) UpsertAnswer(ctx context.Context, arg UpsertAnswerParams) error {
	_, err := q.db.Exec(ctx, upsertAnswer,
		arg.ID,
		arg.UserID,
		arg.Target,
		arg.TargetRef,
		arg.Answer,
		arg.OptionID,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const upsertMark = `-- name: UpsertMark :exec

INSERT INTO user_marks (id, user_id, kind, target, target_ref, color, note, created_at, updated_at, deleted_at, server_updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now())
ON CONFLICT (id) DO UPDATE
SET kind = EXCLUDED.kind, target = EXCLUDED.target, target_ref = EXCLUDED.target_ref, color = EXCLUDED.color,
    note = EXCLUDED.note, updated_at = EXCLUDED.updated_at, deleted_at = EXCLUDED.deleted_at, server_updated_at = now()
WHERE user_marks.user_id = EXCLUDED.user_id AND EXCLUDED.updated_at > user_marks.updated_at
`

type UpsertMarkParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Kind      string
	Target    TargetKind
	TargetRef string
	Color     pgtype.Text
	Note      pgtype.Text
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt pgtype.Timestamptz
}

// ── Sync push (last-write-wins on the client's updated_at) ─
// A row owned by another user is never touched (WHERE on the conflict update).
func (q *Queries) UpsertMark(ctx context.Context, arg UpsertMarkParams) error {
	_, err := q.db.Exec(ctx, upsertMark,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.Target,
		arg.TargetRef,
		arg.Color,
		arg.Note,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const upsertProgress = `-- name: UpsertProgress :exec
INSERT INTO user_progress (user_id, target, target_ref, position, percent, updated_at, server_updated_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (user_id, target, target_ref) DO UPDATE
SET position = EXCLUDED.position, percent = EXCLUDED.percent, updated_at = EXCLUDED.updated_at, server_updated_at = now()
WHERE EXCLUDED.updated_at > user_progress.updated_at
`

type UpsertProgressParams struct {
	UserID    uuid.UUID
	Target    TargetKind
	TargetRef string
	Position  pgtype.Text
	Percent   pgtype.Int4
	UpdatedAt time.Time
}

func (q *Queries) UpsertProgress(ctx context.Context, arg UpsertProgressParams) error {
	_, err := q.db.Exec(ctx, upsertProgress,
		arg.UserID,
		arg.Target,
		arg.TargetRef,
		arg.Position,
		arg.Percent,
		arg.UpdatedAt,
	)
	return err
}
