// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getUser = `-- name: GetUser :one
SELECT id, email, phone, display_name, church, role, ui_lang, parallel_lang, bible_translation,
       text_scale, data_saver, sunset_city, sunset_lat, sunset_lng
FROM users WHERE id = $1
`

type GetUserRow struct {
	ID               uuid.UUID
	Email            pgtype.Text
	Phone            pgtype.Text
	DisplayName      pgtype.Text
	Church           pgtype.Text
	Role             UserRole
	UiLang           string
	ParallelLang     pgtype.Text
	BibleTranslation string
	TextScale        pgtype.Numeric
	DataSaver        bool
	SunsetCity       pgtype.Text
	SunsetLat        pgtype.Numeric
	SunsetLng        pgtype.Numeric
}

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.DisplayName,
		&i.Church,
		&i.Role,
		&i.UiLang,
		&i.ParallelLang,
		&i.BibleTranslation,
		&i.TextScale,
		&i.DataSaver,
		&i.SunsetCity,
		&i.SunsetLat,
		&i.SunsetLng,
	)
	return i, err
}

const languageExists = `-- name: LanguageExists :one
SELECT EXISTS (SELECT 1 FROM languages WHERE code = $1)
`

func (q *Queries) LanguageExists(ctx context.Context, code string) (bool, error) {
	row := q.db.QueryRow(ctx, languageExists, code)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const translationExists = `-- name: TranslationExists :one
SELECT EXISTS (SELECT 1 FROM bible_translations WHERE code = $1)
`

func (q *Queries) TranslationExists(ctx context.Context, code string) (bool, error) {
	row := q.db.QueryRow(ctx, translationExists, code)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateUserSettings = `-- name: UpdateUserSettings :exec
UPDATE users SET
  display_name = $1, church = $2, ui_lang = $3,
  parallel_lang = $4, bible_translation = $5,
  text_scale = $6::float8, data_saver = $7, sunset_city = $8,
  sunset_lat = $9::float8, sunset_lng = $10::float8,
  updated_at = now()
WHERE id = $11
`

type UpdateUserSettingsParams struct {
	DisplayName      pgtype.Text
	Church           pgtype.Text
	UiLang           string
	ParallelLang     pgtype.Text
	BibleTranslation string
	TextScale        float64
	DataSaver        bool
	SunsetCity       pgtype.Text
	SunsetLat        pgtype.Float8
	SunsetLng        pgtype.Float8
	ID               uuid.UUID
}

func (q *Queries) UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) error {
	_, err := q.db.Exec(ctx, updateUserSettings,
		arg.DisplayName,
		arg.Church,
		arg.UiLang,
		arg.ParallelLang,
		arg.BibleTranslation,
		arg.TextScale,
		arg.DataSaver,
		arg.SunsetCity,
		arg.SunsetLat,
		arg.SunsetLng,
		arg.ID,
	)
	return err
}

const upsertUserFromToken = `-- name: UpsertUserFromToken :exec
INSERT INTO users (id, email, display_name, role)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE
SET email        = COALESCE(EXCLUDED.email, users.email),
    display_name = COALESCE(users.display_name, EXCLUDED.display_name),
    role         = EXCLUDED.role,
    updated_at   = CASE WHEN users.role IS DISTINCT FROM EXCLUDED.role OR users.email IS DISTINCT FROM EXCLUDED.email
                        THEN now() ELSE users.updated_at END
`

type UpsertUserFromTokenParams struct {
	ID          uuid.UUID
	Email       pgtype.Text
	DisplayName pgtype.Text
	Role        UserRole
}

// Called on authenticated requests (cached in-process). Email and role follow Keycloak; a display name
// the user set in the app is never overwritten.
func (q *Queries) UpsertUserFromToken(ctx context.Context, arg UpsertUserFromTokenParams) error {
	_, err := q.db.Exec(ctx, upsertUserFromToken,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.Role,
	)
	return err
}
